In [1]:
import numpy as np
import librosa
import soundfile as sf
# Due to 'PySoundFile failed. Trying audioread instead' 
import warnings
warnings.filterwarnings('ignore')

In [53]:
root_path = '/home/nas/DB/CHiME4/data/audio/16kHz/'
category = ['dt05_bus_simu','dt05_caf_simu','dt05_ped_simu','dt05_str_simu','et05_bus_simu','dt05_caf_simu','et05_ped_simu','et05_str_simu','tr05_bus_simu','tr05_caf_simu','tr05_ped_simu','tr05_str_simu']
clean_path = 'isolated/tr05_bth/F02_01DC0204_BTH.CH1.wav'
noise_path = 'backgrounds/BGD_150203_010_PED.CH1.wav'

In [54]:
clean,fs = librosa.load(root_path+clean_path,sr=16000)
noise,fs = librosa.load(root_path+noise_path,sr=16000)

In [55]:
print(type(clean))
print(np.shape(clean))
print(np.size(noise))

<class 'numpy.ndarray'>
(66430,)
29013888


In [56]:
clean_path_pre = 'isolated/tr05_bth/F02_01DC0204_BTH.'
clean_path_post = '.wav'

In [57]:
clean,fs = librosa.load(root_path+clean_path_pre+'CH1'+clean_path_post,sr=16000)
clean = np.expand_dims(clean,axis=1)
for str_ch in ['CH2','CH3','CH4','CH5','CH6'] : 
    tmp_clean,fs = librosa.load(root_path+clean_path_pre+str_ch+clean_path_post,sr=16000)
    tmp_clean = np.expand_dims(tmp_clean,axis=1)
    print(np.shape(clean))
    print(np.shape(tmp_clean))
    clean = np.concatenate([clean,tmp_clean],axis=1)


(66430, 1)
(66430, 1)
(66430, 2)
(66430, 1)
(66430, 3)
(66430, 1)
(66430, 4)
(66430, 1)
(66430, 5)
(66430, 1)


In [48]:
len(clean)

66430

In [51]:
np.shape(clean[4:6])

(2, 6)

# torch.concat

In [2]:
import torch

In [4]:
x = torch.rand(3,2)
y = torch.rand(3,1)
print(x)
print(y)

tensor([[0.1311, 0.4378],
        [0.6601, 0.7852],
        [0.4148, 0.8399]])
tensor([[0.1247],
        [0.3867],
        [0.8876]])


In [7]:
z = torch.cat((x,y),1)
print(z)
print(z.shape)

tensor([[0.1311, 0.4378, 0.1247],
        [0.6601, 0.7852, 0.3867],
        [0.4148, 0.8399, 0.8876]])
torch.Size([3, 3])


In [12]:
nl = torch.nn.Sigmoid()

In [13]:
nl(z)

tensor([[0.5327, 0.6077, 0.5311],
        [0.6593, 0.6868, 0.5955],
        [0.6022, 0.6984, 0.7084]])